version: '3.9'

services:
  db:
    image: postgres
    container_name: pg
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports: 
      - "5432:5432"
  
  web:
    build: .
    container_name: web-app-cotacoes
    restart: always
    volumes:
      - .:/code
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes: 
  postgres_data: