FROM python:3

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN mkdir /code

RUN apt -y update && apt -y install python3 python3-pip python3-psycopg2

RUN pip install --upgrade pip

WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt


COPY . /code/

ENTRYPOINT [ "./.docker/entrypoint.sh", "./.docker/wait-for-it.sh" ]
