# Generated by Django 3.2.7 on 2021-09-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.CharField(max_length=5)),
                ('high', models.CharField(max_length=5)),
                ('low', models.CharField(max_length=5)),
                ('open', models.CharField(max_length=5)),
                ('volume', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallets',
                'verbose_name_plural': 'Wallet',
                'ordering': ('-created_at', 'is_active', 'updated_at'),
            },
        ),
    ]
