# Generated by Django 3.2.7 on 2021-09-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='close',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='high',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='low',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='open',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='volume',
            field=models.CharField(max_length=10),
        ),
    ]
